# tasks file for ubuntu-1804-mariadb-administration
---
- name: databases | create
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8mb4_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
  with_items: "{{ ubuntu_1804_mariadb_administration_databases_present }}"

- name: databases | drop
  mysql_db:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ ubuntu_1804_mariadb_administration_databases_absent }}"
